name: aec-testnet

services:
  erigon:
    image: erigontech/erigon:latest
    container_name: erigon
    user: "root"
    volumes:
      - ./config:/config
      - ./secret:/secret
      - ./data:/data
      - ./logs:/logs
    ports:
      - "30303:30303"
      - "8545:8545"
      - "8551:8551"
      - "6061:6061"
      - "8546:8546"
      - "42069:42069"
    environment:
      - EXTIP=192.168.31.71
      # - EXTIP="$(ip addr show ens5 | grep 'inet ' | awk '{print $2}' | cut -d'/' -f1)"
    command:
      - --config=/config/erigon3.yaml
      - --nat=extip:18.163.81.118
    restart: unless-stopped
    networks:
      - eth-net

  beacon:
    image: gcr.io/offchainlabs/prysm/beacon-chain:stable
    container_name: beacon
    volumes:
      - ./config:/config
      - ./network:/network
      - ./secret:/secret
      - ./data:/data
      - ./logs:/logs
    ports:
      - "13000:13000"
      - "12000:12000/udp"
      - "4000:4000"
      - "3500:3500"
      - "8080:8080"
      - "6060:6060"
    command:
      - --config-file=/config/beacon.yaml
      - --checkpoint-sync-url=http://16.163.97.13:3500
      - --p2p-host-ip=18.163.81.118
      - --suggested-fee-recipient=0x3764eFD87e88A24317a0f4cbbcf15fAE24B2B70c
      - --peer=/ip4/16.163.97.13/tcp/13000/p2p/16Uiu2HAmDmCLraqyx7STiAuG16vXD77orVQ8tLGYDru8DUnFtqT3
      - --peer=/ip4/43.198.212.114/tcp/13000/p2p/16Uiu2HAmHS9Bjihqp8hjMUkaiFZGKioPJ5CMNHfwFmXAAZigtFX6
    restart: unless-stopped
    depends_on:
      - erigon
    networks:
      - eth-net

  validator:
    image: gcr.io/offchainlabs/prysm/validator:stable
    container_name: validator
    volumes:
      - ./config:/config
      - ./network:/network
      - ./secret:/secret
      - ./wallets:/wallets
      - ./data:/data
      - ./logs:/logs
    ports:
      - "8281:8281"
    command:
      - --config-file=/config/validator.yaml
      - --wallet-dir=/wallets/wallet3
      - --suggested-fee-recipient=0x3764eFD87e88A24317a0f4cbbcf15fAE24B2B70c
    restart: unless-stopped
    depends_on:
      - beacon
    networks:
      - eth-net

networks:
  eth-net:
    driver: bridge
